<a href="https://colab.research.google.com/github/NadimMahmud3219/Data-analysis-with-Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array**

In [ ]:
my_list = [1,2,3]

In [ ]:
my_list

[1, 2, 3]

In [ ]:
import numpy as np

In [ ]:
arr =  np.array(my_list)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
twoD = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(twoD)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,2) #np.arange(start,stop,step_size)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

Identity Matrix

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.63325235, 0.82357077, 0.98645808, 0.98277167, 0.70248026])

In [ ]:
np.random.rand(3,3)

array([[0.0104781 , 0.58983008, 0.01452168],
       [0.4060491 , 0.90725083, 0.53289492],
       [0.91156166, 0.37061156, 0.44666637]])

In [ ]:
np.random.randn(5,5)

array([[-1.67285169, -0.45644001, -1.38838863,  0.08282303,  0.04354111],
       [-0.91145516, -0.52681996,  0.93834442, -0.12723335, -0.00281831],
       [-1.13567877, -0.72871287, -1.07638405, -0.11665442,  0.18704712],
       [-0.20703826, -1.41633357,  0.74695351,  1.54050705, -0.26801971],
       [-0.04504218, -0.58567208,  0.23067585,  0.43539148, -0.02896008]])

In [ ]:
np.random.randint(1,100,10)

array([16, 95, 88, 28, 79, 62, 23, 42, 65, 28])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ran_arr = np.random.randint(0,50,10)

In [ ]:
ran_arr

array([16, 12, 23, 39, 28, 27, 12, 48, 36, 48])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

24

In [ ]:
arr.min()

0

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.argmax()

24

In [ ]:
arr.argmin()

0

In [ ]:
new_arr=arr.reshape(5,5)

In [ ]:
new_arr.shape

(5, 5)

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,5)

4

# NumPy Indexing and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0]

0

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:]

array([0, 1, 2, 3, 4])

In [ ]:
arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[0][0]

1

In [ ]:
arr_2d[0]

array([1, 2, 3])

In [ ]:
arr_2d[1][1]

5

In [ ]:
arr_2d[2][1]

8

In [ ]:
arr_2d[2,1] #best way

8

In [ ]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

# Conditional selection

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 5

In [ ]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr<3]

array([1, 2])

In [ ]:
arr_2d = np.arange(50).reshape(5,10)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [ ]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

#NumPy Operations


1.array with array,
2.array with Scalars,
3.Universal array functions

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [ ]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [ ]:
arr.max()

10

In [ ]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

#The End





